#
# Conditional build:
%bcond_without	tests	# do not perform "make test"
#
%include	/usr/lib/rpm/macros.perl
%define		pdir	Stat
%define		pnam	lsMode
Summary:	Stat::lsMode Perl module
Summary(cs):	Modul Stat::lsMode pro Perl
Summary(da):	Perlmodul Stat::lsMode
Summary(de):	Stat::lsMode Perl Modul
Summary(es):	Módulo de Perl Stat::lsMode
Summary(fr):	Module Perl Stat::lsMode
Summary(it):	Modulo di Perl Stat::lsMode
Summary(ja):	Stat::lsMode Perl ¥â¥¸¥å¡¼¥ë
Summary(ko):	Stat::lsMode ÆÞ ¸ðÁÙ
Summary(nb):	Perlmodul Stat::lsMode
Summary(pl):	Modu³ Perla Stat::lsMode
Summary(pt):	Módulo de Perl Stat::lsMode
Summary(pt_BR):	Módulo Perl Stat::lsMode
Summary(ru):	íÏÄÕÌØ ÄÌÑ Perl Stat::lsMode
Summary(sv):	Stat::lsMode Perlmodul
Summary(uk):	íÏÄÕÌØ ÄÌÑ Perl Stat::lsMode
Summary(zh_CN):	Stat::lsMode Perl Ä£¿é
Name:		perl-Stat-lsMode
Version:	0.50
Release:	10
# same as perl
License:	GPL v1+ or Artistic
Group:		Development/Languages/Perl
Source0:	http://www.cpan.org/modules/by-module/%{pdir}/%{pdir}-%{pnam}-%{version}.tar.gz
# Source0-md5:	bf7e558fd0d668dffb2dcd62d21ef635
BuildRequires:	rpm-perlprov >= 4.1-13
BuildRequires:	perl-devel >= 5.6
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Stat::lsMode generates mode and permission strings that look like the
ones generated by the Unix ls -l command.

%description -l pl
Stat::lsMode generuje ³añcuchy z prawami dostêpu w podobnym formacie, w
jakim wy¶wietla je polecenie ls -l.

%prep
%setup -q -n %{pdir}-%{pnam}-%{version}

%build
%{__perl} Makefile.PL \
	INSTALLDIRS=vendor
%{__make}

%{?with_tests:%{__make} test}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README
%{perl_vendorlib}/Stat
%{_mandir}/man3/*
