%include	/usr/lib/rpm/macros.perl
%define	pdir	Stat
%define	pnam	lsMode
Summary:	Stat-lsMode perl module
Summary(pl):	Modu³ perla Stat-lsMode
Name:		perl-Stat-lsMode
Version:	0.50
Release:	8
License:	GPL
Group:		Development/Languages/Perl
Source0:	ftp://ftp.cpan.org/pub/CPAN/modules/by-module/%{pdir}/%{pdir}-%{pnam}-%{version}.tar.gz
BuildRequires:	rpm-perlprov >= 3.0.3-16
BuildRequires:	perl >= 5.6
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Stat-lsMode generates mode and permission strings that look like the
ones generated by the Unix ls -l command.

%description -l pl
Stat-lsMode generuje ³añcuchy z prawami dostêpu w podobnym formacie, w
jakim wy¶wietla je polecenie ls -l.

%prep
%setup -q -n %{pdir}-%{pnam}-%{version}

%build
perl Makefile.PL
%{__make}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install DESTDIR=$RPM_BUILD_ROOT

gzip -9nf README

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc *.gz
%{perl_sitelib}/Stat/lsMode.pm
%{_mandir}/man3/*
